### Sigup user
POST http://{{host}}:{{port}}/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### Signin user
POST http://{{host}}:{{port}}/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### Find a particular user with a given ID
GET http://{{host}}:{{port}}/auth/2

### Find all users with a given email
GET http://{{host}}:{{port}}/auth?email=test@test.com

### Delete a user given id
DELETE http://{{host}}:{{port}}/auth/2

### Update a user
PATCH http://{{host}}:{{port}}/auth/2
Content-Type: application/json

{
  "email": "test@test.com"
}
